[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && node -r dotenv/config dist/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/health"
timeout = 300
